export {default as Order} from './Order/index'
export {default as Blog } from './Blog/index'
export {default as CreateBlog } from './Blog/CreateBlog'
export {default as ShowContact} from './Contact/index'
export {default as Banner } from './Banner/index'
export {default as CreateBanner } from './Banner/CreateBanner'
export {default as UpdateBanner} from './Banner/UpdateBanner'
export {default as UpdateContact} from './Contact/UpdateContact'
export {default as UpdateBlog } from './Blog/UpdateBlog'
export {default as Product } from './Product/index'
export {default as ShowCategory} from './Category/index'
export {default as DetailCategory} from './Category/DetailCategory'
export {default as DeleteCategory} from './Category/DeleteCategory'
export {default as CreateCategory} from './Category/CreateCategory'
export {default as UpdateCategory } from './Category/UpdateCategory'
export {default as UpdateProduct } from './Product/UpdateProduct'
export { default as UpdateOrder} from './Order/UpdateOrder'